#!/usr/bin/env python3
"""Refresh the vendored canonical Indigo documentation.

Indigo publishes two machine-readable docs:
  - https://docs.indigodomo.com/llms.txt       (index: [Title](url): description per page)
  - https://docs.indigodomo.com/llms-full.txt   (full content, sections delimited by
                                                 `--- Title (URL) ---` markers)

This script fetches the monolith, splits it on those markers into small per-page Markdown
files under reference/canonical/ (path mirrors the doc URL), builds INDEX.md from the index,
and stamps VERSION. Skills route into these files for progressive, load-only-what-you-need
reference — never a whole webpage or the 1.5MB monolith in context.

The vendored tree is GENERATED. Never hand-edit a file under reference/canonical/; edit here
and re-run instead.

Usage:
  python3 tools/refresh_canonical.py            # fetch + regenerate reference/canonical/
  python3 tools/refresh_canonical.py --check    # regenerate to a temp dir, diff, exit 1 on drift
  python3 tools/refresh_canonical.py --from-dir DIR   # use local llms.txt / llms-full.txt (offline)
  python3 tools/refresh_canonical.py --allow-version-change   # accept a new Indigo major

Pinned to a specific Indigo version (see VERSION). A published-version change is refused unless
--allow-version-change is passed, so a refresh never silently pulls a new major's content.
Stdlib only — no third-party dependencies.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlsplit
from urllib.request import Request, urlopen

INDEX_URL = "https://docs.indigodomo.com/llms.txt"
FULL_URL = "https://docs.indigodomo.com/llms-full.txt"

# Top-level doc trees to vendor. api/plugin-dev/scripting back the dev + api skills;
# user/plugins back the general /indigo:guide skill (concepts, interfaces incl. Z-Wave,
# remote access, and the bundled plugins).
INCLUDE_PREFIXES = ("api", "plugin-dev", "scripting", "user", "plugins")

SECTION_RE = re.compile(r"^--- (?P<title>.+?) \((?P<url>https?://\S+?)\) ---$")
INDEX_LINK_RE = re.compile(r"^- \[(?P<title>[^\]]+)\]\((?P<url>https?://\S+?)\)(?::\s*(?P<desc>.*))?$")

REPO_ROOT = Path(__file__).resolve().parent.parent
CANONICAL_DIR = REPO_ROOT / "reference" / "canonical"

GEN_HEADER = "<!-- GENERATED from {url} by tools/refresh_canonical.py — DO NOT EDIT. Run the script to refresh. -->\n\n"


# The docs host rejects urllib's default User-Agent (403), so send a conventional one.
USER_AGENT = "Mozilla/5.0 (compatible; indigo-claude-plugin refresh_canonical)"


def fetch(url: str) -> str:
    req = Request(url, headers={"User-Agent": USER_AGENT})
    with urlopen(req, timeout=60) as resp:  # noqa: S310 (trusted vendor URL)
        return resp.read().decode("utf-8")


def url_to_relpath(url: str) -> tuple[str, str] | None:
    """Map a doc URL to (version, 'a/b/c.md'), or None if outside the include set.

    .../2025.2/api/http/            -> ('2025.2', 'api/http.md')
    .../2025.2/api/                 -> ('2025.2', 'api/index.md')
    .../2025.2/plugin-dev/reference/xml/configui/button/ -> (..., '.../configui/button.md')
    """
    parts = [p for p in urlsplit(url).path.split("/") if p]
    if not parts:
        return None
    version, doc_parts = parts[0], parts[1:]
    if not doc_parts or doc_parts[0] not in INCLUDE_PREFIXES:
        return None
    relpath = "/".join(doc_parts) + ".md"
    return version, relpath


def split_full(full_text: str) -> tuple[str, dict[str, tuple[str, str]]]:
    """Split llms-full.txt. Returns (version, {relpath: (url, body)})."""
    lines = full_text.splitlines(keepends=True)
    sections: dict[str, tuple[str, str]] = {}
    version = ""
    cur_url: str | None = None
    cur_relpath: str | None = None
    buf: list[str] = []

    def flush() -> None:
        if cur_relpath and cur_url is not None:
            sections[cur_relpath] = (cur_url, "".join(buf).strip() + "\n")

    for line in lines:
        m = SECTION_RE.match(line.rstrip("\n"))
        if m:
            flush()
            buf = []
            mapped = url_to_relpath(m.group("url"))
            if mapped:
                version = version or mapped[0]
                cur_relpath, cur_url = mapped[1], m.group("url")
            else:
                cur_relpath, cur_url = None, None
        elif cur_relpath:
            buf.append(line)
    flush()
    return version, sections


def build_index(index_text: str) -> str:
    """Rewrite llms.txt into a routing manifest pointing at local vendored paths."""
    out = ["# Canonical documentation index",
           "",
           "GENERATED by tools/refresh_canonical.py from " + INDEX_URL + ".",
           "Each entry points at a local vendored file — load only the page you need.",
           ""]
    for line in index_text.splitlines():
        if line.startswith("## "):
            out.append("")
            out.append(line)
            out.append("")
            continue
        m = INDEX_LINK_RE.match(line.strip())
        if not m:
            continue
        mapped = url_to_relpath(m.group("url"))
        if not mapped:
            continue
        desc = (m.group("desc") or "").strip()
        rel = mapped[1]
        suffix = f" — {desc}" if desc else ""
        out.append(f"- **{m.group('title')}**{suffix} → `reference/canonical/{rel}`")
    return "\n".join(out).rstrip() + "\n"


def generate(out_dir: Path, index_text: str, full_text: str, expected_version: str | None,
             allow_version_change: bool) -> str:
    version, sections = split_full(full_text)
    if not sections:
        sys.exit("ERROR: no sections matched — the canonical format may have changed.")
    if expected_version and version != expected_version and not allow_version_change:
        sys.exit(
            f"ERROR: published version is {version!r} but VERSION pins {expected_version!r}.\n"
            f"Indigo shipped a new major. Re-run with --allow-version-change to accept it "
            f"(and bump the plugin version deliberately)."
        )

    for relpath, (url, body) in sorted(sections.items()):
        dest = out_dir / relpath
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(GEN_HEADER.format(url=url) + body, encoding="utf-8")

    (out_dir / "INDEX.md").write_text(build_index(index_text), encoding="utf-8")

    sha = hashlib.sha256(full_text.encode("utf-8")).hexdigest()
    fetched = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    (out_dir / "VERSION").write_text(
        f"indigo_version: {version}\n"
        f"source_index: {INDEX_URL}\n"
        f"source_full: {FULL_URL}\n"
        f"fetched_utc: {fetched}\n"
        f"sha256_full: {sha}\n"
        f"pages: {len(sections)}\n"
        f"generated_by: tools/refresh_canonical.py\n",
        encoding="utf-8",
    )
    return version


def read_pinned_version() -> str | None:
    vf = CANONICAL_DIR / "VERSION"
    if not vf.exists():
        return None
    for line in vf.read_text(encoding="utf-8").splitlines():
        if line.startswith("indigo_version:"):
            return line.split(":", 1)[1].strip()
    return None


def load_sources(from_dir: str | None) -> tuple[str, str]:
    if from_dir:
        d = Path(from_dir)
        return (d / "llms.txt").read_text(encoding="utf-8"), (d / "llms-full.txt").read_text(encoding="utf-8")
    return fetch(INDEX_URL), fetch(FULL_URL)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="regenerate to a temp dir and diff; exit 1 on drift")
    ap.add_argument("--from-dir", metavar="DIR", help="read local llms.txt / llms-full.txt instead of fetching")
    ap.add_argument("--allow-version-change", action="store_true", help="accept a new pinned Indigo version")
    args = ap.parse_args()

    index_text, full_text = load_sources(args.from_dir)
    pinned = read_pinned_version()

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_dir = Path(tmp)
            generate(tmp_dir, index_text, full_text, pinned, allow_version_change=True)
            drift = []
            new_files = {p.relative_to(tmp_dir) for p in tmp_dir.rglob("*") if p.is_file()}
            old_files = {p.relative_to(CANONICAL_DIR) for p in CANONICAL_DIR.rglob("*") if p.is_file()} \
                if CANONICAL_DIR.exists() else set()
            for rel in sorted(new_files | old_files):
                if rel.name == "VERSION":  # fetched_utc always differs; compare content pages only
                    continue
                a = (CANONICAL_DIR / rel).read_text(encoding="utf-8") if (CANONICAL_DIR / rel).exists() else None
                b = (tmp_dir / rel).read_text(encoding="utf-8") if (tmp_dir / rel).exists() else None
                if a != b:
                    status = "added" if a is None else "removed" if b is None else "changed"
                    drift.append(f"  {status}: reference/canonical/{rel}")
            if drift:
                print("Canonical docs have drifted from the vendored copy:")
                print("\n".join(drift))
                print("\nRun: python3 tools/refresh_canonical.py")
                sys.exit(1)
            print("No drift — vendored canonical matches the live docs.")
            return

    version = generate(CANONICAL_DIR, index_text, full_text, pinned, args.allow_version_change)
    print(f"Refreshed reference/canonical/ from Indigo {version} docs.")


if __name__ == "__main__":
    main()
